development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= Rails.application.secrets.redis_url %>
  channel_prefix: neeto-ui-challenge_production
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
